logging:
    file: logs/application.log
server:
    port: 7777
spring:
    application:
        name: SpringBootZipkin
management:
    metrics:
        web:
            server:
                auto-time-requests: false